fix create folder in a project explorer
spyder-ide/spyder pull request #13740
Opened 2020-09-08 18:46 UTC by akwasigroch

## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

This PR fix an error that prevented creating new folder in project explorer. The cause of the problem was the wrong form of the path generated by the script that looked like:
`OS (C:)\\Users\\Admin\\test_project\\some_module`
This form caused `os.mkdir()` throws an error. 
Now, corrected script produces valid paths like: `C:\\Users\\Admin\\test_project\\some_module`

 

### Issue(s) Resolved

Fixes #13722

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:

2020-09-09 18:26 UTC, ccordoba12 commented
Thanks for your help @akwasigroch! However, I saw that you removed a lot of previous code (which was added to fix another issue) and that's probably not what we want in this case.

@steff456 was in charge of adding that code, so she'll take a more careful look at your work.

2020-09-09 18:47 UTC, steff456 requested changes
Hi @akwasigroch,

This is working as expected and the code is much more compact than mine :) 
I left just one minor comment to reference the issue you are resolving for avoiding regressions in a future.

2020-09-09 18:47 UTC, steff456 commented on spyder/plugins/explorer/widgets/explorer.py
>              # See spyder-ide/spyder#13444
Add `# See spyder-ide/spyder#13722`

2020-09-09 18:59 UTC, pep8speaks commented
Hello @akwasigroch! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`spyder/plugins/explorer/widgets/explorer.py`](https://github.com/spyder-ide/spyder/blob/3f3b433ed22b141208c140e8f4a6e0d6972b323f/spyder/plugins/explorer/widgets/explorer.py):

> [Line 443:1](https://github.com/spyder-ide/spyder/blob/3f3b433ed22b141208c140e8f4a6e0d6972b323f/spyder/plugins/explorer/widgets/explorer.py#L443): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2020-09-09 20:02 UTC, akwasigroch commented
I pushed changes - add requested comment and style fix, that didn't change logic in code. Now, one of the automatic tests fails, I don't know why

2020-09-09 20:17 UTC, steff456 commented
> I pushed changes - add requested comment and style fix, that didn't change logic in code. Now, one of the automatic tests fails, I don't know why

Thanks!!! I will restart them, sometimes they fail spontaneously, so don't worry 😉

2020-09-09 20:18 UTC, steff456 approved these changes
@ccordoba12 this PR is ready to merge as soon the tests pass.

Thanks @akwasigroch for this work!

2020-09-10 04:39 UTC, ccordoba12 commented
> Now, one of the automatic tests fails, I don't know why

Don't worry. I fixed that in PR #13756.

2020-09-10 04:42 UTC, merged