PR: Add tutorial videos to help menu, update link to troubleshooting in docs
spyder-ide/spyder pull request #13895
Opened 2020-09-30 16:02 UTC by juanis2112

## Description of Changes

* [x] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

- Added tutorial videos to help menu pointing to the playlist of spyder tutorials in Youtube 
- Removed Spyder tutorial from help menu as it is already in the help pane (and it will be removed in the future to be integrated with the docs)
- Update link of troubleshooting guide in help menu to point to the new troubleshooting guide in docs

<img width="762" alt="Screenshot 2020-09-30 at 10 56 44 AM" src="https://user-images.githubusercontent.com/18587879/94710379-6857af80-030c-11eb-9d97-72adde3edd08.png">

### Issue(s) Resolved

Fixes #13239 

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:

Juanis2112

2020-09-30 16:02 UTC, pep8speaks commented
Hello @juanis2112! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`spyder/app/mainwindow.py`](https://github.com/spyder-ide/spyder/blob/4b19b91fcc16d2c2f8d4f335f79fb63b5ee503b2/spyder/app/mainwindow.py):

> [Line 1051:1](https://github.com/spyder-ide/spyder/blob/4b19b91fcc16d2c2f8d4f335f79fb63b5ee503b2/spyder/app/mainwindow.py#L1051): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 1052:80](https://github.com/spyder-ide/spyder/blob/4b19b91fcc16d2c2f8d4f335f79fb63b5ee503b2/spyder/app/mainwindow.py#L1052): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (95 > 79 characters)

2020-09-30 16:57 UTC, CAM-Gerlach requested changes
Thanks @juanis2112 , excellent work. I tested this and everything worked and looked great, aside from two minor comments.

Also, don't forget to fixup your two cleanup commits into your first one before merging, to avoid trivial commits with non-descriptive, duplicate messages getting into the permanent history. Thanks!

2020-09-30 16:57 UTC, CAM-Gerlach commented on spyder/app/mainwindow.py
> +        vid_action = create_action(self, _("Tutorial Videos"),
```suggestion
        vid_action = create_action(self, _("Tutorial videos"),
```

For consistency, this should use sentence case, as does every other action in this menu (besides, inexplicably, `Shortcut Summary`) and (most...) other places in Spyder.

2020-09-30 16:57 UTC, CAM-Gerlach commented on spyder/app/mainwindow.py
> +                                   icon=ima.icon('DialogHelpButton'),
This icon repeats the one above, and implies troubleshooting or "rescueing" a user vs. teaching them new things (as tutorial videos are indented to), so it should either be replaced with something more appropriate, like a video icon from QtAwesome, or removed.

2020-09-30 17:21 UTC, juanis2112 commented
/show binder

2020-09-30 17:26 UTC, juanis2112 commented
/show binder

2020-09-30 17:52 UTC, juanis2112 commented
/show binder

2020-09-30 18:10 UTC, ccordoba12 reviewed
Thanks @juanis2112 for this! I left a small comment for you, otherwise looks good.

2020-09-30 18:10 UTC, ccordoba12 commented on spyder/utils/icon_manager.py
> +    'TutorialVideosButton':    [('fa5s.video',), {'color': MAIN_FG_COLOR}],
Let's call this `VideoIcon` to make it a bit more generic (in case we want to use in other places later on).

2020-09-30 19:03 UTC, ccordoba12 approved these changes
Thanks @juanis2112, looks good to me now.

2020-09-30 19:04 UTC, merged

2020-09-30 19:11 UTC, CAM-Gerlach reviewed
For what its worth, I was already in the process of reviewing as soon as the tests passed, and my review was dismissed and it was merged before I had the chance, but after testing this, this looks and works well so approve from me, thanks.

2020-09-30 19:43 UTC, ccordoba12 commented
Sorry, since your previous comments were already addressed, I thought you didn't have more to say. I'll wait for you for next time.

2020-10-01 04:16 UTC, CAM-Gerlach commented
No problem, they were; sorry if I sounded more peeved than I was. I just wanted to give it one last check on Windows after unit tests were green since each platform has some differences in how icons are rendered, which ended up an issue while testing the new video icon we initially chose (which first crashed Spyder on Windows and Linux, then didn't look as we expected). Thanks!