PR: Change screenshot in read me spyder 4
spyder-ide/spyder pull request #15342
Opened 2021-04-19 03:37 UTC by juanis2112

## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

### Issue(s) Resolved

Fixes #

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:
Juanis2112

2021-04-19 16:59 UTC, ccordoba12 approved these changes
Thanks @juanis2112!

2021-04-21 17:36 UTC, ccordoba12 requested changes
Since I have to merge this PR against `5.x` and `master`, please rename `img_src/screenshot.png` to `img_src/screenshot-v4.png`.

With that, the screenshots for Spyder 4 and 5 will be separate.

2021-04-21 17:36 UTC, ccordoba12 commented on README.md
> +![Screenshot of Spyder's main window](https://raw.githubusercontent.com/spyder-ide/spyder/4.x/img_src/screenshot.png)
```suggestion
![Screenshot of Spyder's main window](https://raw.githubusercontent.com/spyder-ide/spyder/4.x/img_src/screenshot-v4.png)
```

2021-11-16 17:11 UTC, dalthviz commented
Closing as oudated

2021-11-16 17:11 UTC, closed without merging